### ISSUE TITLE
scope analysis with escope

### ISSUE THREAD

**Issue by kumavis** [bmeck/tofu#8]
I noticed you're doing some scope analysis - would you be able to use https://github.com/estools/escope?

**Comment by kumavis** [comment]
so i havent played with the js parser ecosystem in awhile and things have certainly changed
here's some things I learned:

seems `estools` repos perhaps fell behind the rapid js language changes
`eslint`, needing to stay ahead, built `espree` on `acorn` and forked `escope` to `eslint-scope`
babel introduced `@babel/parser` (previously `babylon`) which is based on `acorn` and produces a similar AST

For finding "free variables" I also found [acorn-globals](https://github.com/ForbesLindesay/acorn-globals) which works nicely

**Comment by bmeck** [comment]
@kumavis my main problem with existing globals libraries is they are not categorizing the type of usage for the global, things like understanding if `require` is merely being called or being passed around matter.

**Comment by kumavis** [comment]
@bmeck that is really interesting, hadn't considered
